/** Platform installation, official download progress, and synchronized account associations. */
import { useEffect,useMemo,useState } from "react";
import { open } from "@tauri-apps/plugin-dialog";
import { openUrl } from "@tauri-apps/plugin-opener";
import { listen } from "@tauri-apps/api/event";
import { CheckCircle2,Download,ExternalLink,FolderSearch,RefreshCw } from "lucide-react";
import { api } from "../lib/api";
import type { Account,AppError,DownloadProgress,PlatformApp,PlatformLink,SoftwareStatus } from "../lib/types";

const errorMessage=(error:unknown)=>(error as AppError)?.message||"操作失败";
const labels:Record<string,string>={perfectworld:"完美世界", "5e":"5E"};

export function PlatformsPage({accounts,notify}:{accounts:Account[];notify:(kind:"success"|"error",text:string)=>void}){
  const[software,setSoftware]=useState<SoftwareStatus[]>([]);const[progress,setProgress]=useState<Record<string,DownloadProgress>>({});const[links,setLinks]=useState<Record<string,PlatformLink[]>>({});const[detecting,setDetecting]=useState(false);
  const load=async()=>{const[statuses,downloads,accountLinks]=await Promise.all([api.softwareStatuses(),api.downloadProgress(),Promise.all(accounts.map(async account=>[account.id,await api.links(account.id)] as const))]);setSoftware(statuses);setProgress(Object.fromEntries(downloads.map(item=>[item.code,item])));setLinks(Object.fromEntries(accountLinks))};
  useEffect(()=>{void load().catch(error=>notify("error",errorMessage(error)));let unlisten:(()=>void)|undefined;void listen<DownloadProgress>("software-download-progress",event=>{const item=event.payload;setProgress(current=>({...current,[item.code]:item}));if(item.state==="completed"){notify("success",`${software.find(value=>value.code===item.code)?.name||"软件"}安装程序已结束`);void load()}}).then(value=>{unlisten=value});return()=>unlisten?.()},[accounts.length]);
  const detect=async()=>{setDetecting(true);try{const found=await api.discoverPlatformApps();await Promise.all(found.map(item=>api.savePlatformApp(item)));await load();notify("success",`检测完成，找到 ${found.length} 个对战平台客户端`)}catch(error){notify("error",errorMessage(error))}finally{setDetecting(false)}};
  const choose=async(item:SoftwareStatus)=>{if(item.code==="teamspeak3")return;const selected=await open({multiple:false,filters:[{name:"Windows 程序",extensions:["exe"]}],title:`选择${item.name}启动程序`});if(typeof selected!=="string")return;const app:PlatformApp={platformCode:item.code,name:item.name,executablePath:selected,arguments:[],workingDirectory:selected.replace(/[\\/][^\\/]+$/,""),prelaunchCheck:true};try{await api.savePlatformApp(app);await load();notify("success",`${item.name}路径已保存`)}catch(error){notify("error",errorMessage(error))}};
  const download=async(item:SoftwareStatus)=>{if(item.code==="5e"){await openUrl(item.officialUrl);notify("success","已打开 5E 官方下载页");return}try{await api.startSoftwareDownload(item.code)}catch(error){const appError=error as AppError;if(appError.code==="DOWNLOAD_BROWSER_REQUIRED"){await openUrl(item.officialUrl)}else notify("error",errorMessage(error))}};
  const grouped=useMemo(()=>Object.fromEntries(["perfectworld","5e"].map(code=>[code,accounts.filter(account=>(account.platformCodes||[]).includes(code as "perfectworld"|"5e")).map(account=>({account,links:(links[account.id]||[]).filter(link=>link.platformCode===code)}))])),[accounts,links]);
  return <section>
    <header className="page-heading"><div><h1>平台</h1><p>管理客户端安装与官方下载；账号关联来自 Steam 账号详情。</p></div><button className="button secondary" disabled={detecting} onClick={()=>void detect()}><RefreshCw/>{detecting?"正在检测":"重新检测"}</button></header>
    <section className="software-manager"><div className="section-heading"><h2>软件管理</h2><p>安装包下载到专属临时目录，安装程序退出后自动删除。</p></div>{software.map(item=>{const task=progress[item.code];const active=task&&["starting","downloading","installing"].includes(task.state);const percent=task?.total?Math.min(100,Math.round(task.downloaded/task.total*100)):undefined;return <article className="software-row" key={item.code}><div className={`software-icon ${item.code}`}>{item.name.slice(0,2)}</div><div className="software-info"><h3>{item.name}</h3><p title={item.executablePath}>{item.installed?item.executablePath:"尚未安装或未检测到"}</p>{task&&<div className="download-state"><div><i style={{width:`${percent??(active?18:0)}%`}}/></div><span>{task.state==="downloading"?`下载中 ${percent??0}%`:task.state==="installing"?"等待安装完成":task.message||""}</span></div>}</div><span className={`software-status ${item.installed?"installed":"missing"}`}>{item.installed?<><CheckCircle2/>已安装</>:<>未安装</>}</span><div className="software-actions">{item.code!=="teamspeak3"&&<button className="button secondary" onClick={()=>void choose(item)}><FolderSearch/>选择路径</button>}<button className="button primary" disabled={Boolean(active)} onClick={()=>void download(item)}><Download/>{active?"处理中":"官网下载"}</button><button className="icon-button" aria-label={`打开${item.name}官网`} onClick={()=>void openUrl(item.officialUrl)}><ExternalLink/></button></div></article>})}</section>
    <section className="platform-associations"><div className="section-heading"><h2>账号关联</h2><p>在账号详情中编辑，这里按平台同步汇总。</p></div>{(["perfectworld","5e"] as const).map(code=><div className="association-group" key={code}><header><h3>{labels[code]}</h3><span>{grouped[code].length} 个 Steam 账号</span></header><div>{grouped[code].map(({account,links:accountLinks}:{account:Account;links:PlatformLink[]})=><article key={account.id}><strong>{account.personaName||account.alias||account.accountName||"未命名账号"}</strong><small>…{account.steamId64.slice(-6)}</small><span>{accountLinks.map(link=>link.displayName||link.externalId).filter(Boolean).join(" · ")||"已关联，未填写平台昵称"}</span></article>)}{!grouped[code].length&&<p className="muted-copy">还没有关联账号，可在账号详情中添加。</p>}</div></div>)}</section>
  </section>
}
